### ISSUE TITLE
about duplicate masks

### ISSUE THREAD

**Issue by huxycn** [facebookresearch/segment-anything#199]
Thanks for your great work !

When I use SamAutomaticMaskGenerator to generate masks, I found some mask are almost
the same, like below capture

![image](https://user-images.githubusercontent.com/49256066/231759414-eadbc83b-7567-426f-8eca-588057c53419.png)

here is the two mask infomation:
order   area   bbox                          predicted_iou              point_coords    stability_score             crop_box
4         34054 [456, 253, 357, 175] 0.9901902079582214 [[780.0, 387.5]] 0.9854240417480469 [0, 0, 1280, 800]
5         34014 [456, 312, 357, 116] 0.9881749749183655 [[700.0, 412.5]] 0.9856659173965454 [0, 0, 1280, 800]

I see the code use box_nms to do deduplication

but just because upper mask is not clean, has a small stain which marked by a red box, the upper mask, its bounding box is a little larger than the bottom one, their box iou is not larger than 0.7, so the deduplication not work, 

I wonder why dont you directly use mask_iou to do the deduplication

Thanks a lot.

**Comment by HannaMao** [comment]
We chose box nms instead of mask nms due to the considerations of speed. What you could try is to tune `min_mask_region_area` of `SamAutomaticMaskGenerator` (we used 100 when creating SA-1B). It will remove sprinkle pixels shown in your screenshot and fill holes if there are any. It will apply box nms again after the post-processing which most likely will remove the duplicates.
