### ISSUE TITLE
Running the "demo"

### ISSUE THREAD

**Issue by yao-yu1999** [facebookresearch/segment-anything#203]
Running the "demo",Can see the page.But there is no page like the one you demonstrated and  cannot click on the prediction mask. Is it because the file was not loaded completely?
______________________________________________________________________________________________________
![B%%@Z9(RLYC_EE8G JL%7XA](https://user-images.githubusercontent.com/81399827/231923658-c7345d9f-ee40-475f-b0cb-9e75e849533e.png)

![F}{(P0R)ED)T(}KQN`NFY{I](https://user-images.githubusercontent.com/81399827/231923974-91da0e3c-a332-48c0-9c4d-faaec37d17ec.png)

**Comment by iamsret** [comment]
'_embedding.npy' is necessary. You should export the image embedding first. Then, put it in the folder 'src\assets\data'

**Comment by juan-jurado** [comment]
I have tried the Demo and discovered that it only allows segmenting depending on the hover of the mouse. How can I add the other functionality like the ones in the demo? Hover over and click Multi-Mask Mode, Box, and Segment All?

**Comment by dkhanna511** [comment]
Hi., I can click on the masks on the images, but I'm not able to click on anything in order to save my masks. All I can do is visualize the masks like this:
![2023-05-05_14-56_1](https://user-images.githubusercontent.com/30241262/236546161-c5d54d54-b66b-4752-a694-4dd4a8d8403f.png)


I also face this error :
![2023-05-05_14-54](https://user-images.githubusercontent.com/30241262/236546358-4fe3d412-5825-4178-95f7-d4d7a672ef5d.png)

Any help would be appreciated. Thanks!
