### ISSUE TITLE
About object proposal generation on LVIS v1 in Table 4

### ISSUE THREAD

**Issue by yangliu96** [facebookresearch/segment-anything#205]
Thanks for your excellent work! 

I evaluate the object proposal generation of SAM (ViT-H) on LVIS v1, but the result of AR@1000 is 50.5 (not  59.3 reported in the paper). 
I remove the predicted IoU and stability filter and set a 64*64 point grid and 0.9 NMS threshold, which produces about 900 masks per image. 
Maybe there are some differences in the evaluation.  Could you provide the evaluation code？

**Comment by a-F1** [comment]
How do you generate proposals by SAM? I didn't find any relevant code in the repository.

**Comment by ericmintun** [comment]
Thanks for your interest!

We are not intending to release the full evaluation suite as part of this repo at this time. In general, for research-related issues, please reach out to the authors directly instead of using github issues. 

Here are some more details that might be relevant. Masks are ranked by the average of the predicted IoU and stability score when determining what to drop due to the 1000 mask cutoff. We calculate the AR averaged over matching IoU thresholds between 0.5 and 0.95, as in the usual AP/AR calculation for COCO and LVIS. We also calculate the class-agnostic AR, so all ground truth masks are considered to be the same category. Finally, due to the federated nature of LVIS, there may be some subtleties when using existing evaluators intended for class-specific AP; e.g., even when set to be class-agnostic, LVISEval (https://github.com/lvis-dataset/lvis-api/blob/da5f65d16237637d848a51713556c48ca521bc18/lvis/eval.py#L14) will drop predictions with a class label that are neither in the image or exhaustively excluded; this is incorrect for class-agnostic recall.

**Comment by rballachay** [comment]
Hey @yangliu96 what evaluation script did you use? I tried using LVISEval, however ran into multiple problems...
