### ISSUE TITLE
Text prompt?

### ISSUE THREAD

**Issue by asetsuna** [facebookresearch/segment-anything#4]
Amazing work!  However, I didn't find the text prompt support , is there any plan to release it?

**Comment by ORippler** [comment]
From their FAQ.

![image](https://user-images.githubusercontent.com/24656669/230119414-9011a9c9-7314-4bc2-9c06-2a59cb5c82ab.png)

**Comment by ericmintun** [comment]
This is correct, the ability to take text prompts as input is not currently released.

**Comment by LuoYingzhao** [comment]
> This is correct, the ability to take text prompts as input is not currently released.

so， is there a plan to release the text prompts ability?

**Comment by botcs** [comment]
@Rocsg I can imagine that by using only a few examples and a linear projection layer on both spaces one could see if the SAM feature space is aligned with the CLIP feature space or not. If there's no alignment the matching error would be still high.

**Comment by Eli-YiLi** [comment]
We believe directly using the text from text features from CLIP is not good. Because the explainability of CLIP is bad. Using the text features matched with opposite semantic regions lead to wrong results.

This is our work about CLIP's explainability: https://github.com/xmed-lab/CLIP_Surgery

And we can see the self-attention of CLIP links irrelevant regions, with serious noisy across labels.
![fig1](https://user-images.githubusercontent.com/49093246/231665786-bf56a2b4-6923-4022-8778-f4d4b672d476.jpg)
![fig2](https://user-images.githubusercontent.com/49093246/231665881-4e9dcac8-c3c8-4a34-b818-c42e9b2b7aac.jpg)

We suggest using the corrected heatmap to generate points to replace the manual input points.
This is our similarity map from the raw prediction of CLIP and results on SAM.
![fig3](https://user-images.githubusercontent.com/49093246/231666347-a6df3644-ae24-4baf-9d42-515e64cb83d8.jpg)
![fig4](https://user-images.githubusercontent.com/49093246/231666418-02574e64-fb3f-4312-91a5-a5759cdde87c.jpg)

Besides, it's very simple, just use the original CLIP without any fine-tuning or extra supervisions. It's also another solution besides text->box->mask, with requires the least training and supervision cost.

**Comment by jmiemirza** [comment]
https://github.com/luca-medeiros/lang-segment-anything

this project looks interesting

**Comment by jashvira** [comment]
Maybe they were waiting for DinoV2?

**Comment by yassineAlouini** [comment]
It looks like the `Grounded-SAM` paper implement this => https://github.com/IDEA-Research/Grounded-Segment-Anything.

As pointed out by @jashvira, it is based on Grounding-Dino that is itself using Dino.
