### ISSUE TITLE
Why the onnx model have four output  masks

### ISSUE THREAD

**Issue by sanbuphy** [facebookresearch/segment-anything#455]
I would like to ask why during torch prediction, the result can be in the form of [1,3,1024,1024], but when exporting the model to ONNX, it always outputs [1,4,1024,1024]. Where does the extra dimension come from? Why is it necessary? Thank you.

**Comment by idonahum1** [comment]
Hi @sanbuphy ,
When exporting to ONNX, the traced function doesnt not include the selection of the right masks, thus you get 4 masks instead of 3. You can follow this file filter out the desired masks. 
https://github.com/facebookresearch/segment-anything/blob/6fdee8f2727f4506cfbbe553e23b895e27956588/segment_anything/modeling/mask_decoder.py#L102

**Comment by sanbuphy** [comment]
> Hi @sanbuphy , When exporting to ONNX, the traced function doesnt include the selection of the right masks, thus you get 4 masks instead of 3. You can follow this file filter out the desired masks.
> 
> https://github.com/facebookresearch/segment-anything/blob/6fdee8f2727f4506cfbbe553e23b895e27956588/segment_anything/modeling/mask_decoder.py#L102-L107

Hi, Thank you very much. Yes  I have find the usage of slice , It should be set
