### ISSUE TITLE
Is there any other method to load ONNX model without registering the SAM model?

### ISSUE THREAD

**Issue by cris-m** [facebookresearch/segment-anything#519]
I was using the model is the celery docker app, but when registering the SAM model celery crash. The following code 
```python
checkpoint = "sam_vit_h_4b8939.pth"
model_type = "vit_h"
sam = sam_model_registry[model_type](checkpoint=checkpoint)
sam.to(device="cpu")
sam_predictor = SamPredictor(sam)
```

**Comment by heyoeyo** [comment]
The `sam_model_registry` doesn't really register anything. It's just a dictionary which looks up the appropriate 'build_sam...' function, depending on the model size. You can see it in the [build_sam.py](https://github.com/facebookresearch/segment-anything/blob/6fdee8f2727f4506cfbbe553e23b895e27956588/segment_anything/build_sam.py#L47) file.

It's hard to say how to fix the crash without more details. Most likely either the checkpoint pathing is incorrect (i.e. the file is missing or the name/location  doesn't match the provided `checkpoint` variable), or the sizing of the checkpoint data is incorrect (although it looks ok in the code you posted).

**Comment by cris-m** [comment]
I think `vit_h` model was huge, After changing to `vit_l`, celery doesnot crash but when executing the following statement celery crash. 
```python
checkpoint = "sam_vit_l_0b3195.pth"
model_type = "vit_l"
sam = sam_model_registry[model_type](checkpoint=checkpoint)
sam.to(device="cpu")
sam_predictor = SamPredictor(sam)
sam_predictor.set_image(image) # celery crash here
```
I am using `solo` pool which support CPU intensive tasks in a microservices environment like `Docker` or `Kubernetes`. 

`celery worker --app=worker.app --pool=solo`

here the the simple task code I am using

```python


@celery_app.task()
def process_image(image_path):
      checkpoint = "sam_vit_h_4b8939.pth"
      model_type = "vit_h"

      sam = sam_model_registry[model_type](checkpoint=checkpoint)
      ort_session = onnxruntime.InferenceSession('sam_onnx_quantized.onnx')
      sam.to(device="cpu")
      sam_predictor = SamPredictor(sam)

      image = cv2.imread(image_path)
      image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
      
      sam_predictor.set_image(image) # crash here
      image_embedding = sam.get_image_embedding().cpu().numpy()
```

**Comment by EricPacefactory** [comment]
Given that the code gets through the `sam_predictor = SamPredictor(sam)` line as well as the `image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)` line, that suggests that everything should be configured correctly to be able to run the `set_image(...)` part, so it's weird that it exits there. There's nothing in the SAM code that could cause a SIGKILL signal, as far as I can tell. To me, that implies that the process is being shutdown by something else, either the operating system itself (for example due to running out of memory) or maybe something to do with celery (maybe a timeout due to it taking too long?).

One easy thing that's worth trying is using the small (vit_b) model, since that uses a lot less memory than the l/h versions and should help avoid out-of-memory errors, if that's what's happening. The other thing to try would be running the same code without celery (i.e. just copy-pasting it into another script and removing the celery stuff), to see if it runs that way. If it does run, then that narrows the problem down to being a celery config issue, if it doesn't run then at least the error message should be a bit easier to interpret without the celery code catching it.

Beyond that, I don't know much about how celery & pytorch interact, so hopefully someone else can help with that.

**Comment by cris-m** [comment]
Thanks for the reply. I just fix it. The problem was `Docker` resource. I notice when executing the code the CPU usage go to 99% then the task is killed. After adding more resource (4 CPU and 5Gb memory) to my docker engine everything works perfectly.  But I had to also use [celery](https://distributedpython.com/posts/celery-execution-pools-what-is-it-all-about/)  `prefork` instead of `solo` pool.

**Comment by cris-m** [comment]
Thanks for the reply. I just fix it. The problem was `Docker` resources. I noticed when executing the code the CPU usage go to 99% then the task is killed. After adding more resource (4 CPU and 5Gb memory) to my docker engine everything works perfectly.  But I had to also use [celery](https://distributedpython.com/posts/celery-execution-pools-what-is-it-all-about/)  `prefork` instead of `solo` pool.
