### ISSUE TITLE
Mask Boundaries and Colors

### ISSUE THREAD

**Issue by momarms** [facebookresearch/segment-anything#589]
Hi,

I had a segmentation task and used the Automatic Mask Generator for it from the provided [notebook](https://github.com/facebookresearch/segment-anything/blob/main/notebooks/automatic_mask_generator_example.ipynb).
It seems to do what I want quite well but I need to tweak a few things.

When I used the [demo](https://segment-anything.com/demo) with the 'Everything' setting, I saw that it draws a distinct boundary around the objects. 
However, the results from the code I'm using (notebook) are a bit different.
I tried going through the documentations but would appreciate very much if someone can guide me what parameters do I need to adjust or if there's something else I need to do to get similar results i.e. draw a nice boundary.

The second thing is colors of the masks drawn.
Can I somehow control them manually or maybe turn them off at all so that it only draws the boundaries and leaves the rest of the image as is?

Also, I'm not that great with programming and couldn't figure out how to use the dictionary keys. A little info about them would be great too 😅 

Thanks a lot in advance.

_TL;DR_ How to draw (thick) boundaries around the masks and remove mask color.

**Comment by heyoeyo** [comment]
The colored masks are drawn using the `show_anns(...)` function, which is defined in that notebook (near the top), so to draw outlines, you'd need to replace that function. I'm not sure if matplotlib (which is what is being used to handle the drawing) has built-in support for doing outlines, but it's fairly easy to do using opencv.

So anyways, first you'd need to define a new function (in it's own cell) for handling the outline drawing, something like:
```python
def show_outlines(maskgen_data):

    # Bail if there is no mask data
    if len(maskgen_data) == 0:
            return

    # Set up a blank/see-through overlay image, where outlines will be drawn
    ex_mask = maskgen_data[0]["segmentation"]
    img_h, img_w = ex_mask.shape[0:2] 
    overlay_img = np.ones((img_h, img_w, 4))
    overlay_img[:,:,3] = 0

    # Generate outlines for each of the maskgen entries
    for each_gen in maskgen_data:

        # Generate outlines based on the boolean mask images
        boolean_mask = each_gen["segmentation"]
        uint8_mask = 255 * np.uint8(boolean_mask)
        mask_contours, _ = cv2.findContours(uint8_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        if len(mask_contours) == 0:
            continue

        # Draw outlines, using random colors
        outline_opacity = 0.5
        outline_thickness = 2
        outline_color = np.concatenate([np.random.random(3), [outline_opacity]])
        cv2.polylines(overlay_img, mask_contours, True, outline_color, outline_thickness, cv2.LINE_AA)

    # Draw the overlay image
    ax = plt.gca()
    ax.set_autoscale_on(False)
    ax.imshow(overlay_img)
    
    return
```

This is basically the same as the original `show_anns(...)` function, except with a couple new lines for getting the outlines, and I've added some comments to give some idea of what's going on, if that helps. You can change the styling of the outlines by messing with the section that includes `outline_thickness = 2`, for example.

Then all you need to do is use this function when plotting results, instead of the `show_anns(...)` function. So something like:
```python
plt.figure(figsize=(20,20))
plt.imshow(image)
show_outlines(masks)
plt.axis('off')
plt.show()
```

As for the dictionary keys, the `masks` (and `masks2`) variable output from the model is a list, where each list entry contains information about each mask that was generated by the model. That data is stored as a dictionary, which uses 'keys' that allow you to access the info about each of the masks. The keys that are available are listed around the middle of the notebook (i.e. `segmentation`, `area`, `bbox`, etc.). So, long story short, if you want to access info about a mask, you need to specify which list entry you'd like to know about (which will be an integer, `0` being the 'first' mask in the list for example), and then you need to specify which information (key) you'd like to know about (which is a string, like `"area"` for example).

So to get the area of the 'first' (ie. 0-th) mask, you use:
`area_of_mask0 = masks[0]["area"]`

The list ordering of the masks is not meaningful by default, as far as I know (so the first mask isn't special compared to the 2nd or 3rd etc.). Though you can order the masks so that there is some meaning to them. The `show_anns(...)` function actually has an example of this, where they sort by area:
`masks_sorted_by_area = sorted(masks, key=(lambda x: x["area"]), reverse=True)`
So now if you access the first mask, you'd be getting the largest mask (by area):
`biggest_mask = masks_sorted_by_area[0]["area"]`

**Comment by momarms** [comment]
Thanks mate. You're a legend!

**Comment by robotom** [comment]
> The colored masks are drawn using the `show_anns(...)` function, which is defined in that notebook (near the top), so to draw outlines, you'd need to replace that function. I'm not sure if matplotlib (which is what is being used to handle the drawing) has built-in support for doing outlines, but it's fairly easy to do using opencv.
> 
> So anyways, first you'd need to define a new function (in it's own cell) for handling the outline drawing, something like:
> 
> ```python
> def show_outlines(maskgen_data):
> 
>     # Bail if there is no mask data
>     if len(maskgen_data) == 0:
>             return
> 
>     # Set up a blank/see-through overlay image, where outlines will be drawn
>     ex_mask = maskgen_data[0]["segmentation"]
>     img_h, img_w = ex_mask.shape[0:2] 
>     overlay_img = np.ones((img_h, img_w, 4))
>     overlay_img[:,:,3] = 0
> 
>     # Generate outlines for each of the maskgen entries
>     for each_gen in maskgen_data:
> 
>         # Generate outlines based on the boolean mask images
>         boolean_mask = each_gen["segmentation"]
>         uint8_mask = 255 * np.uint8(boolean_mask)
>         mask_contours, _ = cv2.findContours(uint8_mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
>         if len(mask_contours) == 0:
>             continue
> 
>         # Draw outlines, using random colors
>         outline_opacity = 0.5
>         outline_thickness = 2
>         outline_color = np.concatenate([np.random.random(3), [outline_opacity]])
>         cv2.polylines(overlay_img, mask_contours, True, outline_color, outline_thickness, cv2.LINE_AA)
> 
>     # Draw the overlay image
>     ax = plt.gca()
>     ax.set_autoscale_on(False)
>     ax.imshow(overlay_img)
>     
>     return
> ```
> 
> This is basically the same as the original `show_anns(...)` function, except with a couple new lines for getting the outlines, and I've added some comments to give some idea of what's going on, if that helps. You can change the styling of the outlines by messing with the section that includes `outline_thickness = 2`, for example.
> 
> Then all you need to do is use this function when plotting results, instead of the `show_anns(...)` function. So something like:
> 
> ```python
> plt.figure(figsize=(20,20))
> plt.imshow(image)
> show_outlines(masks)
> plt.axis('off')
> plt.show()
> ```
> 
> As for the dictionary keys, the `masks` (and `masks2`) variable output from the model is a list, where each list entry contains information about each mask that was generated by the model. That data is stored as a dictionary, which uses 'keys' that allow you to access the info about each of the masks. The keys that are available are listed around the middle of the notebook (i.e. `segmentation`, `area`, `bbox`, etc.). So, long story short, if you want to access info about a mask, you need to specify which list entry you'd like to know about (which will be an integer, `0` being the 'first' mask in the list for example), and then you need to specify which information (key) you'd like to know about (which is a string, like `"area"` for example).
> 
> So to get the area of the 'first' (ie. 0-th) mask, you use: `area_of_mask0 = masks[0]["area"]`
> 
> The list ordering of the masks is not meaningful by default, as far as I know (so the first mask isn't special compared to the 2nd or 3rd etc.). Though you can order the masks so that there is some meaning to them. The `show_anns(...)` function actually has an example of this, where they sort by area: `masks_sorted_by_area = sorted(masks, key=(lambda x: x["area"]), reverse=True)` So now if you access the first mask, you'd be getting the largest mask (by area): `area_of_biggest_mask = masks_sorted_by_area[0]["area"]`

This is a very helpful post! Regarding the individual masks, tagged with an integer: Is there any sorting technique or other identifying way to pull certain masks out of the "segment everything" technique which creates e.g. 50 masks for a given image. I am using the amg.py script. Perhaps if I remove all other "distractions" from an image it may just pick up the most obvious thing based on some confidence factor. Is this the way to think about it? Because there doesn't seem to be any specific way of prompting SAM based on what I've read on the website. Thanks!

**Comment by momarms** [comment]
Hi,

I need a little more help with something related to the boundaries.

I want to extract the boundary of a mask/segment containing a specified region (or a pixel).
Say I want to find the mask (and then extract it's boundary) that includes the center of the image.
As far as I understand, the masks are not sorted but I can sort by using a dictionary key (e.g. area).
Now the problem is that my scene keeps changing and I am unable to use a specific key to get the mask at the specific location each time.

Any suggestions on how to get this done?

Thanks in advance!

**Comment by heyoeyo** [comment]
There are a few different ways you could filter out masks by some target region...

If it's based on a specific pixel, then you can filter out all masks that don't contain a target pixel with something like:
```python

def check_mask_contains_pixel(mask_result, x, y):
    return mask_result["segmentation"][y, x]

# Get all masks on the image
masks = mask_generator.generate(image)

# Keep only the masks including a target (x,y) pixel
target_x = 123  # or to get x-center: (image.shape[1] // 2)
target_y = 456  # or to get y-center: (image.shape[0] // 2)
target_masks = [m for m in masks if check_mask_contains_pixel(m, target_x, target_y)]
```
This works because the [segmentation key](https://github.com/facebookresearch/segment-anything/blob/6fdee8f2727f4506cfbbe553e23b895e27956588/segment_anything/automatic_mask_generator.py#L147C16-L147C28) stores a boolean mask (i.e. it's an image of 'pixels' that store `True` or `False` values), so if you read a pixel value and it's `True` it means the mask contains that pixel. Though due to the way the amg processing works, I think you'll only ever get 1 or 0 masks this way, which may or may not be what you want.

Another approach would be to define a region (box) and only include masks whose 'center' falls inside this region. This just came up in [another post](https://github.com/facebookresearch/segment-anything/issues/618):
```python
def is_in_roi(mask_result, x1, y1, x2, y2):

    # Get the center point of the box surrounding the given mask
    mask_bbox_xywh = mask_result["bbox"]
    x_cen, y_cen, _, _ = mask_bbox_xywh

    # Check if the center of the result mask is inside the given region of interest box
    is_in_x = (x1 <= x_cen <= x2)
    is_in_y = (y1 <= y_cen <= y2)
    is_in_bbox = (is_in_x and is_in_y)

    return is_in_bbox

# Get all masks on the image
masks = mask_generator.generate(image)

# Filter out results not centered inside of a given region of interest box
roi_bbox_x1y1x2y2 = [200, 200, 400, 550]
masks_in_roi = [m for m in masks if is_in_roi(m, *roi_bbox_x1y1x2y2)]
```
This works because the mask results contain a [bbox](https://github.com/facebookresearch/segment-anything/blob/6fdee8f2727f4506cfbbe553e23b895e27956588/segment_anything/automatic_mask_generator.py#L150C16-L150C20) key, which stores the xywh value of the bounding box surrounding the mask. So this code just checks if the mask `bbox` (x,y) coordinate (the center of the mask) falls inside the given region-of-interest. You can get more than 1 mask this way (if the roi is big enough), unlike checking for a single pixel.

Yet another alternative, and probably the most general approach, would be to describe the region-of-interest using a mask image itself! Then you can check for overlap between masks from the amg results and the provided 'roi mask', using something like:
```python
overlap = np.bitwise_and(roi_mask, mask_to_check)
```
Then you could filter masks based on the amount of overlap found. You could do both the pixel-based and box-region approaches with this approach, along with checking overlap with polygon areas or even more organic shapes (even other segmentation masks!). It's just a lot move involved (drawing, loading, scaling etc. the roi mask).
