### ISSUE TITLE
Getting TypeError: quantize_dynamic() got an unexpected keyword argument 'optimize_model'

### ISSUE THREAD

**Issue by dinushazoomi** [facebookresearch/segment-anything#611]
Hi all, I am trying to quantize the onnx model using the following code section mentioned in the onnx notebook, 
'''
onnx_model_quantized_path = "sam_onnx_quantized_example.onnx"
quantize_dynamic(
    model_input=onnx_model_path,
    model_output=onnx_model_quantized_path,
    optimize_model=True,
    per_channel=False,
    reduce_range=False,
    weight_type=QuantType.QUInt8,
)
onnx_model_path = onnx_model_quantized_path
'''

but getting the following error

'''
TypeError                                 Traceback (most recent call last)
[<ipython-input-7-eb72fa565192>](https://localhost:8080/#) in <cell line: 2>()
      1 onnx_model_quantized_path = "sam_onnx_quantized_example.onnx"
----> 2 quantize_dynamic(
      3     model_input=onnx_model_path,
      4     model_output=onnx_model_quantized_path,
      5     optimize_model=True,

TypeError: quantize_dynamic() got an unexpected keyword argument 'optimize_model'
'''

any help on this would be highly appreciated
Thank you

**Comment by heyoeyo** [comment]
This seems to be caused by a change in newer versions of the `onnxruntime` library. Specifically, the `quantize_dynamic(...)` function no longer has the `optimize_model` argument.

At the moment, the simplest fix is to just delete or comment out the line that's giving the error (i.e. `optimize_model=True,`).

If you're comfortable with modifying the installation, the other fix is to uninstall the current version of the library and then install an older version (version 1.15.1 seems to work). This has the benefit of working longer term in case, for example, the library is updated even further breaking compatibility elsewhere in the future. You can fix the installation with:
```
pip uninstall onnxruntime
pip install onnxruntime==1.15.1
```

**Comment by dinushazoomi** [comment]
great thank you

**Comment by 1214summer** [comment]
It seems not works on me
