### ISSUE TITLE
How to get all the masks in a bounding box?

### ISSUE THREAD

**Issue by xjtupanda** [facebookresearch/segment-anything#618]
Thanks for the great work!

I've played with the official notebook but found no similar implementation.

Is there any way I can draw a box and get all the masks for all the different objects inside the bounding box?

Maybe combine a box prompt and grid points prompts inside the box?

**Comment by heyoeyo** [comment]
If I understand correctly, I think what you're describing could be achieved by cropping the image (to a given bounding box) before running the automatic mask generator on it. You can crop with code using something like:
```python
cropped_image = image[y1:y2, x1:x2, :]
masks = mask_generator.generate(cropped_image)
```
Where x1 & y1 are the top-left coordinates of the bounding box and x2 & y2 are the bottom right coordinates.
It's worth noting that if you try to visualize these masks like the notebook does, they would need to be plotted on top of the _cropped_ image, since they won't line up with the original (uncropped) version without extra padding.

**Comment by xjtupanda** [comment]
> If I understand correctly, I think what you're describing could be achieved by cropping the image (to a given bounding box) before running the automatic mask generator on it. You can crop with code using something like:
> 
> ```python
> cropped_image = image[y1:y2, x1:x2, :]
> masks = mask_generator.generate(cropped_image)
> ```
> 
> Where x1 & y1 are the top-left coordinates of the bounding box and x2 & y2 are the bottom right coordinates. It's worth noting that if you try to visualize these masks like the notebook does, they would need to be plotted on top of the _cropped_ image, since they won't line up with the original (uncropped) version without extra padding.

Thanks for your reply!
I've experimented with this scheme. Though simple, the results are not so good. I guess this is mainly because (1) resolution degradation and (2) incomplete objects (the bounding box may not be so correct).

I've also tried to combine box and point prompts. This strategy achieves better results, but the implementation is trickier.

**Comment by heyoeyo** [comment]
> (2) incomplete objects

Would the goal be to get all objects that may be partly in the bounding box? (i.e. segment things in the box, but allow the masks to extend somewhat out of the box?). In that case, maybe a good option would be to run the automatic mask generator on the whole image as usual, and filter out results that are too far outside of the given bounding box?
The amg outputs include a `bbox` key, which is in xywh format, that represents the bounding box of each of the segmentation masks. These could be used to remove/exclude mask results whose bounding box is not centered somewhere inside of the region of interest box. Something like:
```python
def is_in_roi(mask_result, x1, y1, x2, y2):

    # Get the center point of the box surrounding the given mask
    mask_bbox_xywh = mask_result["bbox"]
    x_cen, y_cen, _, _ = mask_bbox_xywh

    # Check if the center of the result mask is inside the given region of interest box
    is_in_x = (x1 <= x_cen <= x2)
    is_in_y = (y1 <= y_cen <= y2)
    is_in_bbox = (is_in_x and is_in_y)

    return is_in_bbox

# Get all masks on the image
masks = mask_generator.generate(image)

# Filter out results not centered inside of a given region of interest box
roi_bbox_x1y1x2y2 = [200, 200, 400, 550]
masks_in_roi = [mask for mask in masks if is_in_roi(mask, *roi_bbox_x1y1x2y2)]
```

As for the resolution issue, it may not always be practical, but cropping to a square aspect ratio may help? The sam model always scales the input image to 1024x1024 before any further processing and pads any missing space (due to a non-square input image) with zeros, which sort of wastes resolution. Using a square (cropped) input could help to make sure the model is seeing as much meaningful data as possible.

**Comment by xjtupanda** [comment]
> > (2) incomplete objects
> 
> Would the goal be to get all objects that may be partly in the bounding box? (i.e. segment things in the box, but allow the masks to extend somewhat out of the box?). In that case, maybe a good option would be to run the automatic mask generator on the whole image as usual, and filter out results that are too far outside of the given bounding box? The amg outputs include a `bbox` key, which is in xywh format, that represents the bounding box of each of the segmentation masks. These could be used to remove/exclude mask results whose bounding box is not centered somewhere inside of the region of interest box. Something like:
> 
> ```python
> def is_in_roi(mask_result, x1, y1, x2, y2):
> 
>     # Get the center point of the box surrounding the given mask
>     mask_bbox_xywh = mask_result["bbox"]
>     x_cen, y_cen, _, _ = mask_bbox_xywh
> 
>     # Check if the center of the result mask is inside the given region of interest box
>     is_in_x = (x1 <= x_cen <= x2)
>     is_in_y = (y1 <= y_cen <= y2)
>     is_in_bbox = (is_in_x and is_in_y)
> 
>     return is_in_bbox
> 
> # Get all masks on the image
> masks = mask_generator.generate(image)
> 
> # Filter out results not centered inside of a given region of interest box
> roi_bbox_x1y1x2y2 = [200, 200, 400, 550]
> masks_in_roi = [mask for mask in masks if is_in_roi(mask, *roi_bbox_x1y1x2y2)]
> ```
> 
> As for the resolution issue, it may not always be practical, but cropping to a square aspect ratio may help? The sam model always scales the input image to 1024x1024 before any further processing and pads any missing space (due to a non-square input image) with zeros, which sort of wastes resolution. Using a square (cropped) input could help to make sure the model is seeing as much meaningful data as possible.

Thanks for sharing your ideas! I've tried the 'segment all then filter' scheme, and it works better and more stably.

I'll take this strategy as the final option.
