### ISSUE TITLE
Parameter documentation for huggingface config parameters

### ISSUE THREAD

**Issue by TheRealRolandDeschain** [facebookresearch/segment-anything#661]
Hi, I am currently working on a UI Wrapper for the [SAM models on huggingface](https://huggingface.co/facebook/sam-vit-huge). 
Basically, the wrapper lets the user choose images and parameters and then dynamically generates the `preprocessor_config.json` and `config.json` files before running the model inference. 

This works fine with default parameters, however I am wondering if I can find documentation of the parameters in the jsons (short description, value limits, datatype)? This would be quite helpful!

**Comment by heyoeyo** [comment]
I don't know much about the huggingface side of things, so I'd take what I say with a grain of salt... However, it looks like the config files contain a mix of SAM model config parameters and then loads of junk that has nothing to do with the SAM model (but maybe needs to be there for compatibility with the rest of the library?).

For example, there are nonsense entries like: [end-of-sentence token id](https://huggingface.co/facebook/sam-vit-huge/blob/main/config.json#L23) but these are mixed with real SAM parameters like the [layer indices for global attention](https://huggingface.co/facebook/sam-vit-huge/blob/main/config.json#L178). So making sense of the config files probably requires hunting around for which entries are actually relevant.

The `config.json` file has 3 important sections: [mask_decoder_config](https://huggingface.co/facebook/sam-vit-huge/blob/main/config.json#L8), [prompt_encoder_config](https://huggingface.co/facebook/sam-vit-huge/blob/main/config.json#L83) and [vision_config](https://huggingface.co/facebook/sam-vit-huge/blob/main/config.json#L157), these seem to correspond with the model config for classes: [MaskDecoder](https://github.com/facebookresearch/segment-anything/blob/6fdee8f2727f4506cfbbe553e23b895e27956588/segment_anything/modeling/mask_decoder.py#L16), [PromptEncoder](https://github.com/facebookresearch/segment-anything/blob/6fdee8f2727f4506cfbbe553e23b895e27956588/segment_anything/modeling/prompt_encoder.py#L16) and [ImageEncoderViT](https://github.com/facebookresearch/segment-anything/blob/6fdee8f2727f4506cfbbe553e23b895e27956588/segment_anything/modeling/image_encoder.py#L17), respectively. The values in the config file seem to be for the 'huge' variant of the SAM model, which is set within the [build_sam.py](https://github.com/facebookresearch/segment-anything/blob/6fdee8f2727f4506cfbbe553e23b895e27956588/segment_anything/build_sam.py#L14) script. Similarly, the `preprocessor_config.json` seems to reference the preprocessing steps found in the [SAM model class](https://github.com/facebookresearch/segment-anything/blob/6fdee8f2727f4506cfbbe553e23b895e27956588/segment_anything/modeling/sam.py#L164) and parts of the [predictor](https://github.com/facebookresearch/segment-anything/blob/6fdee8f2727f4506cfbbe553e23b895e27956588/segment_anything/predictor.py#L34). So those are the places I would look for understanding the values/ranges of the different settings.

That being said, the values all seem to be related to the model structure. Changing these values makes sense if the goal is to load a different set of weights (like the 'base' or 'large' weights), but would otherwise break the model, since they aren't the kind of values that can be tuned for better performance or anything (at least, for a given set of weights).

**Comment by TheRealRolandDeschain** [comment]
Thank you a lot for the detailed information - this is already quite helpful!

Yes, this is also the first time for me using huggingface. As I understand it, it basically abstracts models away so they can used with a few lines of code - which is actually perfect for my usecase (General web demonstrator for different ML models). So I guess it makes sense, that there is stuff in the configs for compatibility reasons.

**Comment by NielsRogge** [comment]
Hi @TheRealRolandDeschain this is all documented here for instance: https://huggingface.co/docs/transformers/model_doc/sam#transformers.SamMaskDecoderConfig.

**Comment by TheRealRolandDeschain** [comment]
@NielsRogge Thank you I will have a look through the linked documentation!
