### ISSUE TITLE
Tuning SamAutomaticMaskGenerator

### ISSUE THREAD

**Issue by lingondricka2** [facebookresearch/segment-anything#666]
Preferably I want no overlapping masks and I want the masks to cover 100% of the image, how would I do that? Is there any documentation?

**Comment by heyoeyo** [comment]
The closest thing to documentation of the mask generator (that I've seen anyways) is the mask generator's [docstring](https://github.com/facebookresearch/segment-anything/blob/6fdee8f2727f4506cfbbe553e23b895e27956588/segment_anything/automatic_mask_generator.py#L60C1-L95C20) (or otherwise running the amg.py script with the `-h` flag, which gives similar info). Raising the `points-per-side`, reducing the `pred-iou-thresh` and increasing the `box-nms-thresh` should all increase the amount of masks/mask coverage (all things being equal).

However if the goal is specifically no overlap/100% coverage, then it's likely better to use a model that's specifically trained to do that (i.e. a [panoptic segmentation](https://paperswithcode.com/task/panoptic-segmentation) model), rather than SAM which is geared towards prompt-based segmentation.

**Comment by lingondricka2** [comment]
Thank you for your answer, I will try Detectron2 with panoptic segmentation.
