### ISSUE TITLE
Great Project

### ISSUE THREAD

**Issue by yeldarby** [facebookresearch/segment-anything#7]
Really great project. I tried it on a wide range of images and am super impressed.

**Comment by VenoM9078** [comment]
Following.

**Comment by CiaoHe** [comment]
following.

**Comment by timiil** [comment]
flowing

**Comment by acdart** [comment]
following

**Comment by its-jd** [comment]
+1

**Comment by tomebersbach** [comment]
following

**Comment by florentpergoud** [comment]
following

**Comment by iddqd426** [comment]
+1

**Comment by edocod1** [comment]
If you notice, it says "the prompt encoder and mask decoder".
Prompts are the eventual areas/dots of the wanted segmentation features (aka, the "box" you grab with the browser), while the "mask" is the output of the neural network. It means that while the training and detection needs to be done server-side due to the complexity, browsers are capable of decoding the format for the output in reasonable time.

**Comment by mustafaismail22** [comment]
+1

**Comment by Jacobsolawetz** [comment]
following

**Comment by laolihaile** [comment]
following

**Comment by weidacn** [comment]
following

**Comment by kevmo314** [comment]
I've managed to distill out the core of how the demo site works and packaged it up in a Chrome extension. You can find the extension here: https://github.com/kevmo314/magic-copy

**Comment by MiscellaneousStuff** [comment]
And if you want to see how the entire site works, this repository recreates it. Will also include explanations of how it works as well.
https://github.com/MiscellaneousStuff/seg-annotations

**Comment by Jinunmeng** [comment]
very good
